### ISSUE TITLE
Api-Auth breaking changes

### ISSUE THREAD

**Issue by ge1st** [EvidentSecurity/esp_sdk#31]
Hi guys,

The `api-auth` gem released [breaking changes](https://github.com/mgomes/api_auth#important-v200-is-backwards-incompatible-with-the-default-settings-of-v1x-to-address-a-security-vulnerability-see-changelogmd-for-security-update-information) for a Security update in May. 

With the [loose dependency](https://github.com/EvidentSecurity/esp_sdk/blob/22b284d72fe07ac3cfe0e1f4ba38bf39a68f78d4/esp_sdk.gemspec#L41) I receive 401s. Forcing `api-auth` to `~> 1` in my local Gemfile allows for successful authentication again.

**Comment by johnathanludwig** [comment]
Thanks for the notice. We are upgrading our servers to be compatible with the 2.0 version of api-auth, and will hopefully have that change out next week.

**Comment by johnathanludwig** [comment]
Our servers have been updated for compatibility, and today we released a new version of the sdk that locks api-auth to v2. 

In the future we will be removing compatibility with api-auth v1 so please update and let us know if you have any issues.
