### ISSUE TITLE
Next page broken when no params

### ISSUE THREAD

**Issue by johnathanludwig** [EvidentSecurity/esp_sdk#33]
When you request a collection without any parameters and then attempt to call `next_page` a merge error for nil is returned. In the paginated collection it is attempting to merge the previous page params into the original_params, which is nil.

I've tested and received this error on 2.3.0 and 2.5.0.

```ruby
> external_accounts = ESP::ExternalAccount.all
> external_accounts.next_page
NoMethodError: undefined method `merge' for nil:NilClass
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/extensions/active_resource/paginated_collection.rb:75:in `next_page'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/extensions/active_resource/paginated_collection.rb:85:in `next_page!'
	from (espsdk):15
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/commands/console.rb:61:in `block in start'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/commands/console.rb:60:in `catch'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/commands/console.rb:60:in `start'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/commands/commands_tasks.rb:41:in `console'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/lib/esp/commands/commands_tasks.rb:31:in `run_command!'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/esp_sdk-2.5.0/bin/esp:14:in `<top (required)>'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/bin/esp:23:in `load'
	from /Users/johnathanludwig/.rbenv/versions/2.2.4/bin/esp:23:in `<main>
```

**Comment by cityshrimp** [comment]
Just tested ESP SDK v2.6.0, and I'm still seeing an issue with next_page.  Here is the stack trace:

> /Users/cityshrimp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/esp_sdk-2.6.0/lib/esp/extensions/active_resource/paginated_collection.rb:212:in `updated_collection': undefined method `merge' for nil:NilClass (NoMethodError)
	from /Users/cityshrimp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/esp_sdk-2.6.0/lib/esp/extensions/active_resource/paginated_collection.rb:86:in `next_page'
	from 4793.rb:36:in `<main>'

This also happens for "last_page" and "page(n)" as well.
